# -*- coding: utf-8 -*-
# @Time    : 2019/8/20 0020 16:31
# @Author  : 没有蜡笔的小新
# @E-mail  : sqw123az@sina.com
# @FileName: Find the Difference.py
# @Software: PyCharm
# @Blog    ：https://blog.csdn.net/Asunqingwen
# @GitHub  ：https://github.com/Asunqingwen

"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""


def findTheDifference(s: str, t: str) -> str:
	s_dict = {}
	for ss in s:
		s_dict[ss] = s_dict[ss] + 1 if ss in s_dict else 1
	for tt in t:
		if tt not in s_dict or not s_dict[tt]:
			return tt
		else:
			s_dict[tt] -= 1


def findTheDifference1(s: str, t: str) -> str:
	s1 = 0
	s2 = 0
	for i in range(len(s)):
		s1 += ord(s[i])
		s2 += ord(t[i])
	s2 += ord(t[len(s)])
	return chr(s2 - s1)


if __name__ == '__main__':
	s = "abcd"
	t = "abcde"
	result = findTheDifference(s, t)
	print(result)
